# Generated by Django 5.2 on 2025-08-09 09:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('police_id', models.CharField(help_text='Enter your official Police ID (e.g. PNP-12345)', max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Enter a valid Police ID (e.g. PNP-12345).', regex='^PNP-\\d{5}$')])),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone_number', models.CharField(help_text='Enter a valid Philippine mobile number (e.g. 09123456789).', max_length=11, validators=[django.core.validators.RegexValidator(message='Enter a valid Philippine mobile number (e.g. 09123456789).', regex='^09\\d{9}$')])),
                ('rank', models.CharField(choices=[('Commissioned Officers', [('Police General', 'Police General'), ('Police Lieutenant General', 'Police Lieutenant General'), ('Police Major General', 'Police Major General'), ('Police Brigadier General', 'Police Brigadier General'), ('Police Colonel', 'Police Colonel'), ('Police Lieutenant Colonel', 'Police Lieutenant Colonel'), ('Police Major', 'Police Major'), ('Police Captain', 'Police Captain'), ('Police Lieutenant', 'Police Lieutenant')]), ('Non-Commissioned Officers', [('Police Executive Master Sergeant', 'Police Executive Master Sergeant'), ('Police Chief Master Sergeant', 'Police Chief Master Sergeant'), ('Police Senior Master Sergeant', 'Police Senior Master Sergeant'), ('Police Master Sergeant', 'Police Master Sergeant'), ('Police Staff Sergeant', 'Police Staff Sergeant'), ('Police Corporal', 'Police Corporal'), ('Patrolman/Patrolwoman', 'Patrolman/Patrolwoman')])], default='Patrolman/Patrolwoman', help_text='Select your official police rank.', max_length=40)),
                ('officer_photo', models.ImageField(blank=True, help_text='Upload a profile picture of the officer.', null=True, upload_to='officer_photos/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'jpeg', 'png'])])),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeploymentHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('date_time_responded', models.DateTimeField(blank=True, null=True)),
                ('date_time_resolved', models.DateTimeField(blank=True, null=True)),
                ('police', models.ForeignKey(blank=True, db_column='police_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to=settings.AUTH_USER_MODEL, to_field='police_id')),
                ('report', models.ForeignKey(db_column='report_id', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='reports.emergencyreport', to_field='report_id')),
            ],
        ),
    ]
