# Generated by Django 5.2 on 2025-08-21 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='area_vicinity',
            field=models.CharField(blank=True, help_text='Assigned area or vicinity of responsibility (e.g. Quezon City, Barangay 123).', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='designation',
            field=models.CharField(blank=True, help_text='Officer’s current designation/role (e.g. Investigator, Desk Officer, Patrol Unit).', max_length=100, null=True),
        ),
    ]
