# Generated by Django 5.2 on 2025-08-09 09:47

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^RPT-\\d{4}$', 'Report ID must be in format RPT-0000')])),
                ('date_time_reported', models.DateTimeField(default=django.utils.timezone.now)),
                ('location', models.CharField(max_length=255)),
                ('sender', models.CharField(max_length=100)),
                ('crime_category', models.CharField(choices=[('theft', 'Theft'), ('assault', 'Assault'), ('burglary', 'Burglary'), ('vandalism', 'Vandalism'), ('other', 'Other')], max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('closed', 'Closed')], default='pending', max_length=20)),
                ('date_time_responded', models.DateTimeField(blank=True, null=True)),
                ('officers_responded', models.CharField(blank=True, max_length=255)),
                ('date_time_resolved', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-date_time_reported'],
            },
        ),
    ]
