# Generated by Django 5.2 on 2025-08-09 10:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='officers_responded',
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='officers_responded',
            field=models.ManyToManyField(blank=True, help_text='Officers who responded to this report', related_name='reports_responded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
