# Generated by Django 5.2 on 2025-08-14 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_remove_emergencyreport_officers_responded_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='date_time_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='crime_category',
            field=models.CharField(choices=[('assault', 'Assault'), ('sexual_assault', 'Sexual Assault'), ('robbery', 'Robbery'), ('other', 'Other')], max_length=50),
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('unclassified', 'Unclassified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
