# Generated by Django 5.2 on 2025-08-14 09:20

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_emergencyreport_date_time_rejected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='report_id',
            field=models.CharField(editable=False, max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^RPT-\\d{4}$', 'Report ID must be in format RPT-0000')]),
        ),
    ]
