# Generated by Django 5.2 on 2025-08-14 09:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_alter_emergencyreport_report_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='report_id',
            field=models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator('^RPT-\\d{4}-\\d{4}$', 'Report ID must be in format RPT-YYYY-0000')]),
        ),
    ]
