# Generated by Django 5.2 on 2025-08-14 09:32

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_alter_emergencyreport_report_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(unique=True)),
                ('last_number', models.IntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='officers_responded',
            field=models.ManyToManyField(blank=True, related_name='reports_responded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
