# Generated by Django 5.2 on 2025-08-14 09:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_reportsequence_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReportSequence',
        ),
        migrations.AlterField(
            model_name='emergencyreport',
            name='officers_responded',
            field=models.ManyToManyField(blank=True, help_text='Officers who responded to this report', related_name='reports_responded_to', to=settings.AUTH_USER_MODEL),
        ),
    ]
