# Generated by Django 5.2 on 2025-08-14 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0007_delete_reportsequence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('responded', 'Responded'), ('resolved', 'Resolved'), ('unclassified', 'Unclassified'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
