# Generated by Django 5.2 on 2025-08-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0009_alter_emergencyreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('resolved', 'Resolved'), ('unclassified', 'Unclassified'), ('rejected', 'Rejected')], default='active', max_length=20),
        ),
    ]
