# Generated by Django 5.2 on 2025-08-17 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0010_alter_emergencyreport_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='crime_category',
            field=models.CharField(blank=True, choices=[('assault', 'Assault'), ('sexual_assault', 'Sexual Assault'), ('robbery', 'Robbery'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
