# Generated by Django 5.2 on 2025-08-19 08:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('callers', '0001_initial'),
        ('reports', '0011_alter_emergencyreport_crime_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='callers.caller'),
        ),
    ]
