# Generated by Django 4.2.20 on 2025-08-27 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0012_alter_emergencyreport_sender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emergencyreport',
            name='crime_category',
            field=models.CharField(blank=True, choices=[('assault', 'Assault'), ('harassment', 'Harassment'), ('robbery', 'Robbery'), ('other', 'Other')], max_length=50, null=True),
        ),
    ]
