# Generated by Django 4.2.20 on 2025-08-29 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0013_alter_emergencyreport_crime_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='coordinates',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
