# Generated by Django 4.2.20 on 2025-08-30 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0014_emergencyreport_coordinates'),
    ]

    operations = [
        migrations.AddField(
            model_name='emergencyreport',
            name='adminArea',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='countryName',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='locality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='subLocality',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='emergencyreport',
            name='thoroughfare',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
