# Generated by Django 4.2.20 on 2025-09-01 05:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0015_emergencyreport_adminarea_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emergencyreport',
            name='adminArea',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='countryName',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='locality',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='subLocality',
        ),
        migrations.RemoveField(
            model_name='emergencyreport',
            name='thoroughfare',
        ),
    ]
